### ISSUE TITLE
Use real can device

### ISSUE THREAD

**Issue by vbennich** [collabora/k8s-socketcan#2]
Hi!

I am trying this to access a real CAN device but it does not seem to work. The example with vcan works fine.
Is there a guide for a real can device scenario?

Although:

resources:
  limits:
    k8s.collabora.com/can0: 1

Makes sure that the pod is not created. Even though the node has a can0 interface.

Will attach more information if needed.

Thanks!

**Comment by jpc** [comment]
Hey, sorry I've somehow missed your issue when it was posted.

Have you tried using `k8s.collabora.com/socketcan-can0: 1` as your resource name?

Also please make sure you added the names of the allowed CAN interfaces in the [`k8s-socketcan-daemonset.yaml` DaemonSet file](https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-daemonset.yaml) (you'd need to download it, modify and the `kubectl apply` the modified version):
```
containers:
- name: k8s-socketcan
  image: ghcr.io/collabora/k8s-socketcan:latest
  env:
  - name: SOCKETCAN_DEVICES
    value: "can1 can2"
```
By default the list is empty so no actual CAN devices can be moved inside a Pod.

If it does not help then could you please show me the output from:
```
microk8s kubectl logs -l name=k8s-socketcan
```
